### ISSUE TITLE
[master] 2 failing specs from actionmailer

### ISSUE THREAD

**Issue by ahorek** [mikel/mail#1304]
bisected to https://github.com/mikel/mail/pull/607

this is a very old change (2013) that still isn't merged in mail 2.7.x
```
Failure:
BaseTest#test_can_pass_random_headers_in_as_a_hash_to_headers [/home/travis/build/mikel/mail/rails/actionmailer/test/base_test.rb:104]:
Expected: "1234@mikel.me.com"
  Actual: "<1234@mikel.me.com>"

Failure:
BaseTest#test_can_pass_random_headers_in_as_a_hash_to_mail [/home/travis/build/mikel/mail/rails/actionmailer/test/base_test.rb:96]:
Expected: "1234@mikel.me.com"
  Actual: "<1234@mikel.me.com>"
````

it doesn't look like a bug, but tests should be fixed
