### ISSUE TITLE
Test suite wrongly assumes UTF8 encoding

### ISSUE THREAD

**Issue by voxik** [mikel/mail#392]
Hi,

Trying to run test suite on Fedora's build system with Ruby 1.9.3, where LANG=C encoding is set by default, I am observing following errors:

```
  1) Attachments from direct content should assign mime-encoded multibyte filename
     Failure/Error: @mail.attachments['てすと.txt'] = File.read(fixture('attachments', 'てすと.txt'))
     ArgumentError:
       invalid byte sequence in US-ASCII
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/core_extensions/string.rb:13:in `=~'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/core_extensions/string.rb:13:in `!~'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/core_extensions/string.rb:13:in `blank?'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/body.rb:36:in `initialize'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:1909:in `new'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:1909:in `process_body_raw'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:1155:in `body'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:2000:in `init_with_hash'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:123:in `initialize'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/attachments_list.rb:78:in `new'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/attachments_list.rb:78:in `[]='
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/spec/mail/attachments_list_spec.rb:42:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
  2) Mail::Message initialization should be able to parse an email missing an encoding
     Failure/Error: Mail::Message.new(File.read(fixture('emails', 'error_emails', 'must_supply_encoding.eml')))
     ArgumentError:
       invalid byte sequence in US-ASCII
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/core_extensions/string.rb:4:in `gsub'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/core_extensions/string.rb:4:in `to_crlf'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:1887:in `raw_source='
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:2006:in `init_with_string'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:125:in `initialize'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/spec/mail/message_spec.rb:74:in `new'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/spec/mail/message_spec.rb:74:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
  3) Mail::Message initialization should be able to parse every email example we have without raising an exception
     Failure/Error: errors.should be_false
       expected true to be false
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/expectations/handler.rb:21:in `handle_matcher'
     # /usr/share/gems/gems/rspec-expectations-2.8.0/lib/rspec/expectations/extensions/kernel.rb:12:in `should'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/spec/mail/message_spec.rb:94:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun'
  4) Mail::Message initialization should not raise a warning on having non US-ASCII characters in the header (should just handle it)
     Failure/Error: Mail::Message.new(File.read(fixture('emails', 'plain_emails', 'raw_email_string_in_date_field.eml')))
     ArgumentError:
       invalid byte sequence in US-ASCII
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/core_extensions/string.rb:4:in `gsub'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/core_extensions/string.rb:4:in `to_crlf'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:1887:in `raw_source='
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:2006:in `init_with_string'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/lib/mail/message.rb:125:in `initialize'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/spec/mail/message_spec.rb:99:in `new'
     # /builddir/build/BUILD/rubygem-mail-2.4.4/usr/share/gems/gems/mail-2.4.4/spec/mail/message_spec.rb:99:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:80:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:173:in `with_around_hooks'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example.rb:77:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:355:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:351:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:337:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/example_group.rb:338:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:80:in `run_in_process'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:69:in `run'
     # /usr/share/gems/gems/rspec-core-2.8.0/lib/rspec/core/runner.rb:10:in `block in autorun
```

Thank you.
