### ISSUE TITLE
OpenSSL::SSL::SSLError (hostname does not match the server certificate):

### ISSUE THREAD

**Issue by nozpheratu** [mikel/mail#550]
I have my Rails application configured to use 'none' for openssl verification, but I'm still running into the error message:

> OpenSSL::SSL::SSLError (hostname does not match the server certificate)

I'm using the following configuration:

**config/intializers/setup_mail.rb**

``` ruby
if Rails.env != 'test'
  email_settings = YAML::load(File.open("#{Rails.root.to_s}/config/email.yml"))
  ActionMailer::Base.smtp_settings = email_settings[Rails.env] unless email_settings[Rails.env].nil?
end
```

**config/email.yml**

``` yaml
production:
  address: smtp.mts.net
  port: 25
  authentication: plain
  user_name: username
  password: secret
  enable_starttls_auto: true
  openssl_verify_mode: none
```

**config/environments/production.rb**

``` ruby
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.default_url_options = { :host => 'example.com' }
```

ActionMailer seems to completely disregard `openssl_verify_mode: none`
